"""empty message

Revision ID: 3e74d1131afa
Revises: 8e14ff9d42f9
Create Date: 2020-09-03 15:11:35.382490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e74d1131afa'
down_revision = '8e14ff9d42f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmp_dashboard_star',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='看板ID'),
    sa.Column('dmp_user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('dmp_dashboard_id', sa.Integer(), nullable=False, comment='文件夹ID'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dmp_dashboard_star')
    # ### end Alembic commands ###
