"""empty message

Revision ID: 64ef688cc751
Revises: baf357d0c1c8
Create Date: 2020-10-22 14:29:45.865905

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '64ef688cc751'
down_revision = 'baf357d0c1c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('dmp_chart', sa.Column('charts_position', sa.Text(), nullable=False, comment='图表布局数据'))
    op.alter_column('dmp_chart', 'chart_name',
               existing_type=mysql.VARCHAR(length=64),
               comment='图表名称',
               existing_comment='图标名称',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dmp_chart', 'chart_name',
               existing_type=mysql.VARCHAR(length=64),
               comment='图标名称',
               existing_comment='图表名称',
               existing_nullable=False)
    op.drop_column('dmp_chart', 'charts_position')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
