"""empty message

Revision ID: 8e14ff9d42f9
Revises: e4fc72d074ca
Create Date: 2020-08-24 11:21:53.720965

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8e14ff9d42f9'
down_revision = 'e4fc72d074ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmp_dashboard', sa.Column('changed_on', sa.DateTime(), nullable=True, comment='最后修改时间'))
    op.drop_column('dmp_dashboard', 'hanged_on')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmp_dashboard', sa.Column('hanged_on', mysql.DATETIME(), nullable=True, comment='最后修改时间'))
    op.drop_column('dmp_dashboard', 'changed_on')
    # ### end Alembic commands ###
