"""empty message

Revision ID: aa501b84ab88
Revises: cc2d277c1a3c
Create Date: 2020-09-22 11:10:05.009873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa501b84ab88'
down_revision = 'cc2d277c1a3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.alter_column('dmp_chart', 'chart_data',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='数据')
    op.alter_column('dmp_chart', 'dmp_data_table_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='数据表ID')
    op.alter_column('dmp_chart', 'params',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='图表参数')
    op.alter_column('dmp_chart', 'query_string',
               existing_type=mysql.TEXT(),
               nullable=True,
               existing_comment='查询语句')
    op.alter_column('dmp_chart', 'update_interval',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='时间间隔时间')
    op.alter_column('dmp_chart', 'update_unit',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='时间间隔单位，0小时，1日，3周')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dmp_chart', 'update_unit',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='时间间隔单位，0小时，1日，3周')
    op.alter_column('dmp_chart', 'update_interval',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='时间间隔时间')
    op.alter_column('dmp_chart', 'query_string',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='查询语句')
    op.alter_column('dmp_chart', 'params',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='图表参数')
    op.alter_column('dmp_chart', 'dmp_data_table_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='数据表ID')
    op.alter_column('dmp_chart', 'chart_data',
               existing_type=mysql.TEXT(),
               nullable=False,
               existing_comment='数据')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
