"""empty message

Revision ID: baf357d0c1c8
Revises: 41bb51ddd971
Create Date: 2020-10-20 18:53:47.532845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'baf357d0c1c8'
down_revision = '41bb51ddd971'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dmp_kylin_table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('kylin_cube_name', sa.String(length=64), nullable=False, comment='cube名称'),
    sa.Column('kylin_models_name', sa.String(length=64), nullable=False, comment='model名称'),
    sa.Column('db_table_name', sa.String(length=64), nullable=False, comment='数据库内数据表名称'),
    sa.Column('is_kylin', sa.Integer(), nullable=True, comment='是否是Kylin表,0否，1是， 2转化中 '),
    sa.Column('created_on', sa.DateTime(), nullable=False, comment='创建时间'),
    sa.Column('changed_on', sa.DateTime(), nullable=True, comment='修改时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kylin_cube_name'),
    sa.UniqueConstraint('kylin_models_name')
    )
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('dmp_data_table', sa.Column('is_kylin', sa.Integer(), nullable=True, comment='是否是Kylin表,0否，1是， 2转化中 '))
    op.add_column('dmp_data_table', sa.Column('kylin_info_id', sa.Integer(), nullable=True, comment='Kylin信息表ID'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dmp_data_table', 'kylin_info_id')
    op.drop_column('dmp_data_table', 'is_kylin')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    op.drop_table('dmp_kylin_table')
    # ### end Alembic commands ###
