"""empty message

Revision ID: cc2d277c1a3c
Revises: 3e74d1131afa
Create Date: 2020-09-21 09:31:03.309402

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc2d277c1a3c'
down_revision = '3e74d1131afa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_apscheduler_jobs_next_run_time', table_name='apscheduler_jobs')
    op.drop_table('apscheduler_jobs')
    op.add_column('dmp_chart', sa.Column('update_task_id', sa.String(length=64), nullable=True, comment='更新任务ID'))
    op.alter_column('dmp_data_service', 'source_dmp_data_table_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True,
               existing_comment='数据表ID')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dmp_data_service', 'source_dmp_data_table_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False,
               existing_comment='数据表ID')
    op.drop_column('dmp_chart', 'update_task_id')
    op.create_table('apscheduler_jobs',
    sa.Column('id', mysql.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_apscheduler_jobs_next_run_time', 'apscheduler_jobs', ['next_run_time'], unique=False)
    # ### end Alembic commands ###
